# mkdocs.yml
site_name: Audim

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.tracking

plugins:
  - mkdocstrings
  - search
  - minify
  - glightbox
  - mkdocs-jupyter:
      include_source: True


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: 'index.md'
  - Setup:
    - Installation: 'setup/installation.md'
    - Development: 'setup/development.md'
  - Audim:
    - Index: 'audim/index.md'
    - Aud2Sub:
      - Core: 'audim/aud2sub/core.md'
      - Transcribers:
        - Base: 'audim/aud2sub/transcribers/base.md'
        - Podcast: 'audim/aud2sub/transcribers/podcast.md'
    - Sub2Pod:
      - Core: 'audim/sub2pod/core.md'
      - Layouts:
        - Base: 'audim/sub2pod/layouts/base.md'
        - Podcast: 'audim/sub2pod/layouts/podcast.md'
      - Elements:
        - Header: 'audim/sub2pod/elements/header.md'
        - Profile: 'audim/sub2pod/elements/profile.md'
        - Text: 'audim/sub2pod/elements/text.md'
        - Watermark: 'audim/sub2pod/elements/watermark.md'
      - Effects:
        - Transitions: 'audim/sub2pod/effects/transitions.md'
        - Highlights: 'audim/sub2pod/effects/highlights.md'
    - Utils:
      - Playback: 'audim/utils/playback.md'
      - Subtitle: 'audim/utils/subtitle.md'
      - Extract: 'audim/utils/extract.md'
  - Dev Blog:
    - Index: 'devblog/index.md'
    - v0.0.7: 'devblog/v0.0.7.md'
    - v0.0.6: 'devblog/v0.0.6.md'
    - v0.0.5: 'devblog/v0.0.5.md'
    - v0.0.3: 'devblog/v0.0.3.md'
    - v0.0.2: 'devblog/v0.0.2.md'
    - v0.0.1: 'devblog/v0.0.1.md'

repo_url: https://github.com/mratanusarkar/audim
